# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c03d47e0c1a8a59d1a87a2b144cc50e7a655bb7b9a02c6663ed1e33d50dbc87d141a22a6407458cee70701a7d109d1cc244a8c1d51018debe96da115b887117

test:
  secret_key_base: c41c10b15d9fca589d2de100a85e994b62371cef565df76ec8f73c1e071393224c380d2b87ea5f26e528c7cd61511924915b3853084a204874d5f0dada194b2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
